#Server
server:
  port: 8090

# Database
spring:
  banner:
    location: banner.txt
  main:
    banner-mode: console

  datasource:
#    url: jdbc:h2:mem:testdb
    url: jdbc:mysql://localhost:3306/test?useSSL=false
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQLDialect
springdoc:
  api-docs:
    path: /swagger-ui.html
