#Server
server:
  port: 8090

# Database
spring:
  banner:
    location: banner.txt
  main:
    banner-mode: console

  datasource:
#    url: jdbc:h2:mem:testdb
    url: jdbc:mysql://localhost:3306/spring_test?useSSL=false
    username: sammy
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver
    jpa:
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false
